name: s04actindomiddleware-dev

services:
  actindomiddleware-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: actindomiddleware-dev
    ports:
      - "2234:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Dashboard=Data Source=App_Data/dashboard.dev.db
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Information
      - ASPNETCORE_LOGGING__LOGLEVEL__MICROSOFT=Warning
    volumes:
      - actindo_data_dev:/app/App_Data
      - ./.actindo-refresh-token.dev:/app/.actindo-refresh-token
    networks:
      - monitoring_default
    restart: unless-stopped

networks:
  monitoring_default:
    external: true

volumes:
  actindo_data_dev:
    name: actindo_data_dev
